### PR TITLE
Added example to infer PaliGemma on Android using HF & Gradio Client API

### PR DESCRIPTION
**Pull request by NSTiwari**
Added example to infer PaliGemma on Android using HF & Gradio Client API. Please review.

### CODE REVIEW

**Comment by bebechien** [comment]
It looks like this PR is mixed up with PR #35

**Comment by NSTiwari** [comment]
Oops, let me close this PR and create a new one afresh.

**Comment by NSTiwari** [comment]
@bebechien: I'm closing this PR and will create a new one. Meanwhile, could you please review #35?

**Comment by NSTiwari** [comment]
Closing the PR.

**Pull request closed without merging**
