### PR TITLE
Fixed "Run in Google Colab" Links for Gemma TPU Inference Tutorials

### PR DESCRIPTION
**Pull request by selamw1**
Somehow the "Run in Google Colab" links were broken, and this PR fixes them.

### CODE REVIEW

**Comment by windmaple** [comment]
Can you just use a simple editor (e.g., vim/emacs) to fix the link w/o touching other parts of the notebook? There are many diffs but all that is needed is to remove an extra 's' in the link.

Also, we are looking into a better merging approach. In the meanwhile, could you pull in the latest main before sending PR?

**Comment by selamw1** [comment]
> Can you just use a simple editor (e.g., vim/emacs) to fix the link w/o touching other parts of the notebook? There are many diffs but all that is needed is to remove an extra 's' in the link.
> 
> Also, we are looking into a better merging approach. In the meanwhile, could you pull in the latest main before sending PR?

For the first notebook removing 's' would fix for the broken link: `gemma_inference_on_tpu.ipynb`

However, for the second notebook (titled: `gemma_data_parallel_inference_in_jax_tpu.ipynb`), its a replica of the first notebook, the whole notebook needs to be changed.

**Comment by bebechien** [comment]
I resolved the conflict. Can you run nbfmt for both notebooks to fix the formatting issue?

**Review by bebechien — APPROVED** [review]
lgtm except the nbfmt issue

**Pull request merged**
